; https://stackoverflow.com/questions/34183658/inorder-traversal-in-lisp (inorderverif)
(defun inorderverif (l)
	(case (cadr l)
		(0 (values (list (car l)) (cddr l)))
		(1 (multiple-value-bind (left-subtree rest-of-list) (inorderverif (cddr l)) (values (nconc left-subtree (list (car l))) rest-of-list)))
		(t	(multiple-value-bind (left-subtree rest-of-list) (inorderverif (cddr l))
				(multiple-value-bind (right-subtree rest-of-rest) (inorderverif rest-of-list)
					(values (nconc left-subtree (list (car l)) right-subtree) rest-of-rest))
			)
		)
	)
)

(defun ret (l)
	(cond
		((null l) nil)
		((= (cadr l) 2) (list (car l) (cadr l)))
		(t (append (list (car l) (cadr l)) (ret (cddr l))))
	)
)

(defun del (l)
	(cond
		((null l) nil)
		((= (cadr l) 2) (cddr l))
		(t (del (cddr l)))
	)
)

(defun inorderx (l s c)
	(cond
		((null l) c)
		((not (= (cadr l) 0)) (inorderx (cddr l) (append (list (car l) (cadr l)) s) c))
		(t (inorderx (cddr l) (del s) (append c (list (car l) (cadr l)) (ret s))))
	)
)

(defun onlynodes (l)
	(cond
		((null l) nil)
		(t (cons (car l) (onlynodes (cddr l))))
	)
)

(defun inorder (l)
	(onlynodes (inorderx l nil nil))
)

(write (inorder '(A 2 B 0 C 2 D 0 E 0)))
(write-line "")
(write (inorderverif '(A 2 B 0 C 2 D 0 E 0)))
(write-line "")
(write (inorder '(A 2 B 2 D 0 E 2 H 0 I 0 C 2 F 0 G 0)))
(write-line "")
(write (inorderverif '(A 2 B 2 D 0 E 2 H 0 I 0 C 2 F 0 G 0)))
(write-line "")
(write (inorder '(A 2 B 1 C 2 D 1 G 1 I 0 E 1 F 0 H 2 J 0 K 0)))
(write-line "")
(write (inorderverif '(A 2 B 1 C 2 D 1 G 1 I 0 E 1 F 0 H 2 J 0 K 0)))
(write-line "")
(write (inorder '(A 2 B 1 D 1 G 1 I 0 C 2 E 1 H 2 J 0 K 0 F 0)))
(write-line "")
(write (inorderverif '(A 2 B 1 D 1 G 1 I 0 C 2 E 1 H 2 J 0 K 0 F 0)))
(write-line "")
(write (inorder '(F 2 B 2 A 0 D 2 C 0 E 0 G 1 I 1 H 0)))
(write-line "")
(write (inorderverif '(F 2 B 2 A 0 D 2 C 0 E 0 G 1 I 1 H 0)))
(write-line "")